CREATE DATABASE db_projetopoo
GO
USE db_projetopoo
GO
DROP TABLE IF EXISTS TB_EMPRESTIMO;
DROP TABLE IF EXISTS TB_USUARIO;
DROP TABLE IF EXISTS TB_REAGENTE;

CREATE TABLE TB_USUARIO
(
	ID_USUARIO INT IDENTITY(1,1) NOT NULL,
	DS_NOME    VARCHAR(20)       NOT NULL,
	DS_SENHA   VARCHAR(15)       NOT NULL,
	DS_EMAIL   VARCHAR(50)	     NOT NULL,
	DS_TIPO    CHAR(1)           NOT NULL,
	DS_STATUS  CHAR(1)			 NOT NULL
	PRIMARY KEY (ID_USUARIO)
);

CREATE TABLE TB_REAGENTE(
	ID_REAGENTE	 INT IDENTITY(1,1) NOT NULL,
	NM_DESCRICAO VARCHAR(50)	   NOT NULL,
	CD_INTERNO   VARCHAR(10)	   NOT NULL,
	NR_CAS		 VARCHAR(15),
	QT_PESO		 NUMERIC(12,4)      NOT NULL,
	UN_MEDIDA    VARCHAR(2)        NOT NULL,
	DS_OBS		 VARCHAR(100),
	DS_STATUS    CHAR(1)		   NOT NULL,
	PRIMARY KEY (ID_REAGENTE)
);

CREATE TABLE TB_EMPRESTIMO(
	ID_EMPRESTIMO INT IDENTITY(1,1) NOT NULL,
	ID_USUARIO    INT			    NOT NULL,
	ID_REAGENTE   INT				NOT NULL,
	QT_PESO       NUMERIC(7,2)      NOT NULL,
	DT_EMPRESTIMO DATE				NOT NULL,
	DS_STATUS     CHAR(1)		    NOT NULL,
	PRIMARY KEY(ID_EMPRESTIMO)
);