USE db_projetopoo
GO

--TABELA USUÁRIOS
INSERT INTO TB_USUARIO(DS_NOME, DS_SENHA, DS_EMAIL, DS_TIPO, DS_STATUS)
VALUES('VITOR', '123456', 'VITOR@HOTMAIL.COM', 'A', 'A')

INSERT INTO TB_USUARIO(DS_NOME, DS_SENHA, DS_EMAIL, DS_TIPO, DS_STATUS)
VALUES('GUILHERME', '147258', 'GUI@HOTMAIL.COM', 'U', 'A')

--TABELA REAGENTES
INSERT INTO TB_REAGENTE(NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_OBS, DS_STATUS)
VALUES ('BETA-CASEÍNA', 'Q21', '9000-71-9', 1, 'G', 'O REAGENTE ESTÁ NO CONGELADOR (LAB 01)','A')

INSERT INTO TB_REAGENTE(NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_STATUS)
VALUES ('1,2 FENILENODIAMINA', 'R26', '95-54-5', 100, 'G','A')

INSERT INTO TB_REAGENTE(NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_OBS, DS_STATUS)
VALUES ('1.1-DIFENIL-2-PICRIL-HIDRAZIL', 'V5', '1898-66-4', 1, 'G', 'O REAGENTE ESTÁ NA GELADEIRA (SALA TÉCNICA)','A')

INSERT INTO TB_REAGENTE(NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_STATUS)
VALUES ('1-NAFTOL', 'T30', '90-15-3', 775, 'G', 'A')

INSERT INTO TB_REAGENTE(NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_STATUS)
VALUES ('1-PROPANOL', '49', '71-23-8', 2000, 'ML', 'A')

INSERT INTO TB_REAGENTE(NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_STATUS)
VALUES ('2,4-DINITRO-FENILHIDRAZINA', 'T29', '119-26-6', 0.3, 'G', 'A')

INSERT INTO TB_REAGENTE(NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_STATUS)
VALUES ('2,4-PENTANEDIONE', '30', '600-14-6', 600, 'ML', 'A')

INSERT INTO TB_REAGENTE(NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_STATUS)
VALUES ('4-(METHYLAMINO) PHENOL SULFATE', 'R28.1', '55-55-0', 500, 'G', 'A')

INSERT INTO TB_REAGENTE(NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_STATUS)
VALUES ('4-ANISALDEÍDO', '32', '123-11-5', 350, 'ML', 'A')

INSERT INTO TB_REAGENTE(NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_STATUS)
VALUES ('4-DIMETILAMINOBENZALDEÍDO', 'Q10', '100-10-7', 350, 'G', 'A')

INSERT INTO TB_REAGENTE(NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_STATUS)
VALUES ('ACETANILIDA PURÍSSIMA', 'Q50', '103-84-4', 494, 'G', 'A')

INSERT INTO TB_REAGENTE(NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_STATUS)
VALUES ('ACETATO DE AMÔNIO', 'P4', '631-61-8', 469, 'ML', 'A')

INSERT INTO TB_REAGENTE(NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_STATUS)
VALUES ('ACETATO DE BÁRIO', 'B14', '543-80-6', 200, 'G', 'A')

INSERT INTO TB_REAGENTE(NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_OBS, DS_STATUS)
VALUES ('ACETATO DE ETILA', '39', '141-78-6', 7300, 'ML', 'O REAGENTE ESTÁ NO ARMÁRIO DO LAB 01 (PERTO DA JANELA) E ALMOXARIFADO', 'A')

INSERT INTO TB_REAGENTE(NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_STATUS)
VALUES ('FENOLFTALEÍNA', 'T1', '77-09-8', 240, 'G', 'A')

INSERT INTO TB_REAGENTE(NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_STATUS)
VALUES ('VERMELHO DE FENOL', 'T22', '143-74-8', 125, 'G', 'A')

--TABELA EMPRESTIMO
INSERT INTO TB_EMPRESTIMO (ID_USUARIO, ID_REAGENTE, QT_PESO, DT_EMPRESTIMO, DS_STATUS)
VALUES (1, 2, 10, '2019-11-27', 'A')

INSERT INTO TB_EMPRESTIMO (ID_USUARIO, ID_REAGENTE, QT_PESO, DT_EMPRESTIMO, DS_STATUS)
VALUES (1, 5, 120, '2019-11-27', 'A')

INSERT INTO TB_EMPRESTIMO (ID_USUARIO, ID_REAGENTE, QT_PESO, DT_EMPRESTIMO, DS_STATUS)
VALUES (1, 5, 135.35, '2019-11-28', 'A')

INSERT INTO TB_EMPRESTIMO (ID_USUARIO, ID_REAGENTE, QT_PESO, DT_EMPRESTIMO, DS_STATUS)
VALUES (2, 4, 15, '2019-11-29', 'A')

INSERT INTO TB_EMPRESTIMO (ID_USUARIO, ID_REAGENTE, QT_PESO, DT_EMPRESTIMO, DS_STATUS)
VALUES (2, 9, 175, '2019-11-29', 'A')

INSERT INTO TB_EMPRESTIMO (ID_USUARIO, ID_REAGENTE, QT_PESO, DT_EMPRESTIMO, DS_STATUS)
VALUES (2, 2, 80.22, '2019-11-29', 'A')