USE db_projetopoo
GO

-- AUTENTICAÇÃO DE USUÁRIOS
DROP PROCEDURE IF EXISTS SP_AUTENTICAR_USUARIO
GO

CREATE PROCEDURE SP_AUTENTICAR_USUARIO
	@DS_NOME  VARCHAR(20),
	@DS_SENHA VARCHAR(15)
AS
BEGIN
	SELECT 
		ID_USUARIO, DS_NOME, DS_SENHA, DS_EMAIL, DS_TIPO 
	FROM 
		TB_USUARIO
	WHERE
		DS_NOME = @DS_NOME
	AND
		DS_SENHA = @DS_SENHA
	AND 
		DS_STATUS = 'A'
END;

GO
-- CONSULTA DE USUÁRIOS CADASTRADOS
DROP PROCEDURE IF EXISTS SP_CONSULTA_USUARIOS
GO

CREATE PROCEDURE SP_CONSULTA_USUARIOS
	@DS_NOME VARCHAR(20)
AS
BEGIN
	SELECT
		ID_USUARIO, DS_NOME, DS_SENHA, DS_EMAIL, DS_TIPO
	FROM 
		TB_USUARIO
	WHERE
		DS_NOME LIKE '%'+ @DS_NOME +'%'
	AND
		DS_STATUS = 'A'
END;

--CADASTRO DE NOVOS USUÁRIOS
GO
DROP PROCEDURE IF EXISTS SP_CADASTRO_USUARIO
GO

CREATE PROCEDURE SP_CADASTRO_USUARIO
	@DS_NOME  VARCHAR(20),
	@DS_SENHA VARCHAR(15),
	@DS_EMAIL VARCHAR(50),
	@DS_TIPO  CHAR(1)
AS
BEGIN
	INSERT INTO TB_USUARIO (DS_NOME, DS_SENHA, DS_EMAIL, DS_TIPO, DS_STATUS)
	VALUES (@DS_NOME, @DS_SENHA, @DS_EMAIL, @DS_TIPO, 'A')

	SELECT @@IDENTITY;
END;

--ALTERAÇÃO DE CADASTRO DE USUÁRIO
GO
DROP PROCEDURE IF EXISTS SP_ALTERACAO_USUARIO
GO

CREATE PROCEDURE SP_ALTERACAO_USUARIO
	@ID_USUARIO INT,
	@DS_NOME    VARCHAR(20),
	@DS_SENHA   VARCHAR(15),
	@DS_EMAIL   VARCHAR(50),
	@DS_TIPO    CHAR(1)
AS
BEGIN
	UPDATE 
		TB_USUARIO
	SET
		DS_NOME = @DS_NOME,
		DS_SENHA = @DS_SENHA,
		DS_EMAIL = @DS_EMAIL,
		DS_TIPO = @DS_TIPO
	WHERE
		ID_USUARIO = @ID_USUARIO
	SELECT @@ROWCOUNT;
END;

--EXCLUSÃO DE USUÁRIOS
GO
DROP PROCEDURE IF EXISTS SP_EXCLUSAO_USUARIO
GO

CREATE PROCEDURE SP_EXCLUSAO_USUARIO
	@ID_USUARIO INT
AS
BEGIN
	UPDATE
		TB_USUARIO
	SET
		DS_STATUS = 'I'
	WHERE
		ID_USUARIO = @ID_USUARIO
	SELECT @@ROWCOUNT;
END;

GO
-- CONSULTA DE REAGENTES CADASTRADOS
DROP PROCEDURE IF EXISTS SP_CONSULTA_REAGENTE
GO

CREATE PROCEDURE SP_CONSULTA_REAGENTE
	@NM_DESCRICAO VARCHAR(20)
AS
BEGIN
	SELECT
		ID_REAGENTE, NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_OBS
	FROM 
		TB_REAGENTE
	WHERE
		NM_DESCRICAO LIKE '%'+ @NM_DESCRICAO +'%'
	AND
		DS_STATUS = 'A'
END;

GO
-- CONSULTA DE REAGENTES CADASTRADOS ESPECIFICO
DROP PROCEDURE IF EXISTS SP_CONSULTA_REAGENTE_ESPECIFICO
GO

CREATE PROCEDURE SP_CONSULTA_REAGENTE_ESPECIFICO
	@ID_REAGENTE INT
AS
BEGIN
	SELECT
		ID_REAGENTE, NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_OBS
	FROM 
		TB_REAGENTE
	WHERE
		ID_REAGENTE = @ID_REAGENTE
END;

--CADASTRO DE NOVOS REAGENTES
GO
DROP PROCEDURE IF EXISTS SP_CADASTRO_REAGENTE
GO

CREATE PROCEDURE SP_CADASTRO_REAGENTE
	@NM_DESCRICAO   VARCHAR(50),
	@CD_INTERNO		VARCHAR(15),
	@NR_CAS			VARCHAR(50),
	@QT_PESO		VARCHAR(50),
	@UN_MEDIDA		CHAR(1),
	@DS_OBS			VARCHAR(100)

AS
BEGIN
	INSERT INTO TB_REAGENTE (NM_DESCRICAO, CD_INTERNO, NR_CAS, QT_PESO, UN_MEDIDA, DS_OBS, DS_STATUS)
	VALUES (@NM_DESCRICAO, @CD_INTERNO, @NR_CAS, @QT_PESO, @UN_MEDIDA, @DS_OBS, 'A')

	SELECT @@IDENTITY;
END;

--ALTERAÇÃO DE CADASTRO DE REAGENTES
GO
DROP PROCEDURE IF EXISTS SP_ALTERACAO_REAGENTE
GO

CREATE PROCEDURE SP_ALTERACAO_REAGENTE
	@ID_REAGENTE	INT,
	@NM_DESCRICAO   VARCHAR(50),
	@CD_INTERNO		VARCHAR(15),
	@NR_CAS			VARCHAR(50),
	@QT_PESO		VARCHAR(50),
	@UN_MEDIDA		CHAR(1),
	@DS_OBS			VARCHAR(100)
AS
BEGIN
	UPDATE 
		TB_REAGENTE
	SET
		NM_DESCRICAO = @NM_DESCRICAO,   
		CD_INTERNO = @CD_INTERNO,	
		NR_CAS = @NR_CAS,				
		QT_PESO	= @QT_PESO,		
		UN_MEDIDA =	@UN_MEDIDA,		
		DS_OBS = @DS_OBS
	WHERE
		ID_REAGENTE = @ID_REAGENTE
	SELECT @@ROWCOUNT;
END;

--EXCLUSÃO DE REAGENTES
GO
DROP PROCEDURE IF EXISTS SP_EXCLUSAO_REAGENTE
GO

CREATE PROCEDURE SP_EXCLUSAO_REAGENTE
	@ID_REAGENTE INT
AS
BEGIN
	UPDATE
		TB_REAGENTE
	SET
		DS_STATUS = 'I'
	WHERE
		ID_REAGENTE = @ID_REAGENTE
	SELECT @@ROWCOUNT;
END;

GO
-- CONSULTA DE EMPRESTIMOS CADASTRADOS
DROP PROCEDURE IF EXISTS SP_CONSULTA_EMPRESTIMO
GO

CREATE PROCEDURE SP_CONSULTA_EMPRESTIMO
	@NM_DESCRICAO VARCHAR(20)
AS
BEGIN
	SELECT 
		ID_EMPRESTIMO, ID_USUARIO, E.ID_REAGENTE, E.QT_PESO, R.NM_DESCRICAO, DT_EMPRESTIMO
	FROM
		TB_EMPRESTIMO AS E INNER JOIN TB_REAGENTE AS R ON R.ID_REAGENTE = E.ID_REAGENTE
	WHERE
		R.NM_DESCRICAO LIKE '%' + @NM_DESCRICAO + '%'
	AND
		E.DS_STATUS = 'A'
	ORDER BY 
		DT_EMPRESTIMO DESC
END;

--CADASTRO DE NOVOS EMPRESTIMOS
GO
DROP PROCEDURE IF EXISTS SP_CADASTRO_EMPRESTIMO
GO

CREATE PROCEDURE SP_CADASTRO_EMPRESTIMO
	@ID_USUARIO		INT,
	@ID_REAGENTE	INT,
	@QT_PESO		NUMERIC(7,2)

AS
BEGIN
	INSERT INTO TB_EMPRESTIMO (ID_USUARIO, ID_REAGENTE, QT_PESO, DT_EMPRESTIMO, DS_STATUS)
	VALUES (@ID_USUARIO, @ID_REAGENTE, @QT_PESO, GETDATE(), 'A')

	SELECT @@IDENTITY;
END;

--ALTERAÇÃO DE CADASTRO DE EMPRESTIMOS
GO
DROP PROCEDURE IF EXISTS SP_ALTERACAO_EMPRESTIMO
GO

CREATE PROCEDURE SP_ALTERACAO_EMPRESTIMO
	@ID_EMPRESTIMO	INT,
	@ID_USUARIO		INT,
	@ID_REAGENTE	INT,
	@QT_PESO		NUMERIC(7,2)
AS
BEGIN
	UPDATE 
		TB_EMPRESTIMO
	SET
		ID_USUARIO = @ID_USUARIO,   
		ID_REAGENTE = @ID_REAGENTE,	
		QT_PESO = @QT_PESO
	WHERE
		ID_EMPRESTIMO = @ID_EMPRESTIMO
	SELECT @@ROWCOUNT;
END;

--EXCLUSÃO DE EMPRESTIMOS
GO
DROP PROCEDURE IF EXISTS SP_EXCLUSAO_EMPRESTIMO
GO

CREATE PROCEDURE SP_EXCLUSAO_EMPRESTIMO
	@ID_EMPRESTIMO INT
AS
BEGIN
	UPDATE
		TB_EMPRESTIMO
	SET
		DS_STATUS = 'I'
	WHERE
		ID_EMPRESTIMO = @ID_EMPRESTIMO
	SELECT @@ROWCOUNT;
END;

--EMPRESTIMO DE REAGENTES
GO
DROP PROCEDURE IF EXISTS SP_EMPRESTIMO_REAGENTE
GO

CREATE PROCEDURE SP_EMPRESTIMO_REAGENTE
	@ID_REAGENTE	INT,
	@QT_PESO		NUMERIC(7,2)
AS
BEGIN
	UPDATE 
		TB_REAGENTE
	SET		
		QT_PESO	= QT_PESO - @QT_PESO	
	WHERE
		ID_REAGENTE = @ID_REAGENTE
	SELECT @@ROWCOUNT;
END;

--EXCLUSAO DE EMPRESTIMO DE REAGENTES
GO
DROP PROCEDURE IF EXISTS SP_EXCLUSAO_EMPRESTIMO_REAGENTE
GO

CREATE PROCEDURE SP_EXCLUSAO_EMPRESTIMO_REAGENTE
	@ID_REAGENTE	INT,
	@QT_PESO		NUMERIC(7,2)
AS
BEGIN
	UPDATE 
		TB_REAGENTE
	SET		
		QT_PESO	= QT_PESO + @QT_PESO	
	WHERE
		ID_REAGENTE = @ID_REAGENTE
	SELECT @@ROWCOUNT;
END;

--CONSULTA DE EMPRESTIMOS REALIZADOS(RELATÓRIO)
GO 
DROP PROCEDURE IF EXISTS SP_RELATORIO_EMPRESTIMO
GO

CREATE PROCEDURE SP_RELATORIO_EMPRESTIMO
	@DT_INICIO DATE,
	@DT_FIM    DATE
AS
BEGIN
	SELECT 
		ID_EMPRESTIMO, E.ID_USUARIO, U.DS_NOME, R.NM_DESCRICAO, E.QT_PESO, R.UN_MEDIDA, DT_EMPRESTIMO
	FROM
		TB_EMPRESTIMO AS E 
		INNER JOIN TB_REAGENTE AS R ON R.ID_REAGENTE = E.ID_REAGENTE
		INNER JOIN TB_USUARIO AS U ON U.ID_USUARIO = E.ID_USUARIO
	WHERE
		E.DT_EMPRESTIMO BETWEEN @DT_INICIO AND @DT_FIM
	AND
		E.DS_STATUS = 'A'
	ORDER BY 
		DT_EMPRESTIMO DESC
END;

--CONSULTA DE EMPRESTIMOS ESPECIFICO
GO 
DROP PROCEDURE IF EXISTS SP_CONSULTA_EMPRESTIMO_ESPECIFICO
GO

CREATE PROCEDURE SP_CONSULTA_EMPRESTIMO_ESPECIFICO
	@ID_EMPRESTIMO INT
AS
BEGIN
	SELECT 
		ID_EMPRESTIMO, ID_USUARIO, E.ID_REAGENTE, E.QT_PESO, R.NM_DESCRICAO, DT_EMPRESTIMO
	FROM
		TB_EMPRESTIMO AS E INNER JOIN TB_REAGENTE AS R ON R.ID_REAGENTE = E.ID_REAGENTE
	WHERE
		ID_EMPRESTIMO = @ID_EMPRESTIMO
END;